spring:
  application:
    name: microservice-api-gateway
server:
  port: 8763
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

zuul:
  max:
    host:
      connections: 500
  host:
    connect-timeout-millis: 1000
    socket-timeout-millis: 6000
  prefix: /api
  sensitiveHeaders:
  routes:
    user:
      path: /user/**
      serviceId: news-user
      stripPrefix: false # 表示转发时附带前缀