#server:
#  port: 8761                    # 指定该Eureka实例的端口
#
#eureka:
#  instance:
#    hostname: discovery         # 指定该Eureka实例的主机名
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  instance:
    hostname: discovery                # 指定该Eureka实例的主机名
  server:
    enable-self-preservation: false    # 关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 清理间隔（单位毫秒，默认是60*1000）
  client:
    registerWithEureka: false # 不向注册中心注册自己
    fetchRegistry: false # 关闭服务检索

    serviceUrl:
      #         defaultZone: http://discovery:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756